import { customError } from "@/helpers/AppErr";
import apiError from "@/helpers/errors";

const authService = {
	test: async () => {},
};
export default authService;
